library("ggplot2")
args = commandArgs(trailingOnly=TRUE)
p<-read.delim( file = args[1], row.names = NULL, header = FALSE, sep = "\t")
#head(p)

p_count<- table(p$V5)
#head(p_count)
for_hist = as.data.frame(p_count)
#head(for_hist)

hist = ggplot(for_hist, aes(x=Freq)) + geom_histogram(binwidth = 1) + theme_classic(base_size = 30)
hist = hist + labs( y = "Number of peaks", x = "Number of motifs") + scale_y_continuous(expand = c(0, 0))
plot(hist)
png( args[2] , height = 800, width = 1024 )
plot( hist )
dev.off()
pdf( args[3], useDingbats=FALSE)
plot( hist )
dev.off()